[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_program = "Bqp8qbntEFEK37Hou9MMsoWgPGzP99AS1NDq4EUjtxTs"
goal_manager = "8sgn8F6gPbJ1bdNYZf6FLdQ59DBUA389aEmHw785NQfT"
reward-token = "5i5RFgcDnaQa1gGFy5pW9S8XN9rhuX73NFgowTtwyqD6"
stake_vault = "8iT2i4bqebs8BKq7Rc9rmWxBMquzmEwTrv1Nx3pU61Q7"
verification_program = "yQGgkBcMkjYy8rrtgdLRjtjnPvJdS5YJET1MRHCv1CX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
