[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

# Apply optimizations for all workspace packages
[profile.release.package."*"]
opt-level = 3
incremental = false
codegen-units = 1
